assist_project/assist_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'django_assist/', include('django_assist.urls')),
    url(r'^admin/', admin.site.urls),
]

assist_project/django_assist/urls.py
from django.conf.urls import url

from . import views

app_name = 'django_assist'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<step_id>[0-9]+)/run_step/$', views.run_step, name='run_step'),
]

assist_project/django_assist/models.py
from django.db import models


# Create your models here.

class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField('CreatedOn', auto_now_add=True)
    modified = models.DateTimeField('ModifiedOn', auto_now=True)

    class Meta:
        abstract = True


class Project(TimeStampedModel):
    project_name = models.CharField(max_length=500)

    def __str__(self):
        return ("Project {}".format(self.project_name))


class StepStatus(models.Model):
    status_name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return "[{}]".format(self.status_name)


class Step(TimeStampedModel):
    step_name = models.CharField(max_length=200)
    step_status = models.ForeignKey(StepStatus, null=True)
    step_order = models.IntegerField()

    def __str__(self):
        return ("Step {}: {} {}".format(self.step_order, self.step_name, self.step_status))


class Command(TimeStampedModel):
    step = models.ForeignKey(Step, on_delete=models.CASCADE)
    command_text = models.CharField(max_length=1000)
    output_text = models.TextField(default="",blank=True)

    def __str__(self):
        return ("{} [{}]".format(self.command_text,self.step.step_name))


class CommandOutput(TimeStampedModel):
    command = models.ForeignKey(Command, on_delete=models.CASCADE)
    output_text = models.TextField()

    def __str__(self):
        return ("Output {}".format(self.output_text))

assist_project/django_assist/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Step, Command

class IndexView(generic.ListView):
    template_name = 'django_assist/index.html'
    context_object_name = 'step_list'

    def get_queryset(self):
        """Return the steps in order."""
        return Step.objects.order_by('step_order')



class DetailView(generic.DetailView):
    model = Step
    template_name = 'django_assist/detail.html'

class ResultsView(generic.DetailView):
    model = Step
    template_name = 'django_assist/results.html'

def run_step(request, step_id):
    step = get_object_or_404(Step, pk=step_id)
    try:
        selected_command = step.command_set.get(pk=request.POST['command'])
    except (KeyError, Command.DoesNotExist):
        # Redisplay the step run form.
        return render(request, 'django_assist/detail.html', {
            'step': step,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_command.output_text = "example"
        selected_command.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('django_assist:results', args=(step.id,)))

assist_project/django_assist/templates/django_assist/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'django_assist/style.css' %}" />
    <title>{% block title %}Django Assistant: A UI for Django commands{% endblock %}</title>
</head>

<body>
    <div class="page-wrapper">
	    <section class="intro" id="zen-intro">
	    	<header role="banner">
				<h1>{% block header %}Django Assistant{% endblock %}</h1>
				<h2>{% block subheading %}The <abbr title="User Interface">UI</abbr> for Django Commands{% endblock %}</h2>
			</header>
		    <div id="content">
		        {% block content %}{% endblock %}
		    </div>
		</section>
	</div>
    
    <aside id="sidebar" class="sidebar" role="complementary">
    	<div class="design-selection" id="design-selection">
    	<nav role="navigation">
					
        {% block sidebar %}
        <ul>
            <li><a href="/django_assist">Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock %}
        </nav>
        </div>
    </aside>

</body>
</html>

assist_project/django_assist/templates/django_assist/detail.html
{% extends "django_assist/base.html" %}

{% block title %}Django Assistant: Step List {% endblock %}

{% block subheading %}Command List{% endblock %}

{% block content %}

<h3>{{ step.step_name }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'django_assist:run_step' step.id %}" method="post">
{% csrf_token %}
{% for command in step.command_set.all %}
    <input type="radio" name="command" id="command{{ forloop.counter }}" value="{{ command.id }}" />
    <label for="command{{ forloop.counter }}">{{ command.command_text }}</label><br />
{% endfor %}
<input type="submit" value="Run" />
</form>

<h4>Previous runs</h4>
<ul>
    {% for command in step.command_set.all %}
        {% if command.output_text|length > 0 %}
        <li>{{command.command_text }}:{{ command.output_text }} </li>
        {% else %}
        <li>{{command.command_text }}:Not Run </li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

assist_project/django_assist/templates/django_assist/index.html
{% extends "django_assist/base.html" %}

{% block title %}Django Assistant: Step List {% endblock %}

{% block content %}

<h3>Steps</h3>
<div class="explanation" id="zen-explanation" role="article">
    {% if step_list %}
        <ul>
        {% for step in step_list %}
            <li>Step {{step.step_order }} {{ step.step_status }}: <a href="/django_assist/{{ step.id }}/">{{ step.step_name }}</a> </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No steps are available.</p>
    {% endif %}
</div>

{% endblock %}

assist_project/django_assist/templates/django_assist/results.html
<div class="basic">
    {% include "./detail.html" %}
    <h5>You have run '{{ step.step_name }}'. Check results above</h5>
    
</div>